### ISSUE TITLE
Does not work with Epever XTRA 3210N

### ISSUE THREAD

**Issue by mager33** [chickey/RS485-WiFi-EPEver#17]
No live data, no historical data, but load switch works. Any hints how to debug? (not sure if it relates to #6, as ther is no sun right now)

**Comment by chickey** [comment]
Hi Martin,
         I’ve not experienced that before.  If you plug it into a PC at the same time as it is connected to the charge controller then you can open up a connection the com port and see the output.  It should periodically report the readings, will be interesting to see if they show up there.

Thanks
Colin

**Comment by mager33** [comment]
Actually, it was a bod contact on a breadboard setup - took me some time to figure out... finally switched to a ESPhome based solution to stay in the HomeAssistannt ecosystem. But your would have worked, too.
