### ISSUE TITLE
as any one tested this on epever upower ?

### ISSUE THREAD

**Issue by patmtp35** [chickey/RS485-WiFi-EPEver#22]

**Comment by chickey** [comment]
The registers are different for the upower inverters so it will be a lot of changes but i have created a esphome config which shall work.  Pins D1 and D2 need tied together to work with ESPHome.

https://github.com/chickey/RS485-WiFi-EPEver/blob/master/epever-upower.yaml

**Comment by patmtp35** [comment]
many thanks i haven t seen your respone before sorry :( 
i'll test it
