### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by chickey** [chickey/RS485-WiFi-EPEver#5]
[enhancement - danger of overcommitting myself] - Would you be interested in having a checkbox later so that if MQTT was enabled it could also publish the magic incantation so that it showed up in Home Assistant? ie https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by galapogos01** [comment]
Fantastic idea, love HA!

**Comment by bronzeblood** [comment]
Yeah for sure, would make things easier

**Comment by Duckshousemacservice** [comment]
Great project !  i just ordered the board and just flashed a wemos. home assistant discovery is working great , But home assistant now has its own energy module where you need to use specific classes for the values.  

As your code is right now i cant add the values to home assistant energy module.

is that something you would spend time on ?

would be great and make many peoples life easier :-) 

this is the doc for the classes:  https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics
