### ISSUE TITLE
'AsyncWiFiManager' was not declared in this scope

### ISSUE THREAD

**Issue by mph88** [chickey/RS485-WiFi-EPEver#7]
The code as is gives the above compilation error in Arduino IDE with most recent 2.7.4 ESP8266 library.

Change:
`WiFiManager.h` to `ESPAsyncWifiManager.h` and use the library: alanswx/ESPAsyncWiFiManager

**Comment by chickey** [comment]
I do not call WiFiManager.h , i call #include <ESPAsyncWiFiManager.h> it's in the main file.  If you include the library from the link mentioned in the comments it compiles fine as is.

**Comment by mph88** [comment]
If you #include <ESPAsyncWiFiManager.h>, tzapu/WiFiManager does not include ESPAsyncWiFiManager.h, but instead includes WiFiManager.h. If you do use that repo and change to #include <WiFiManager.h>, then you'll get an error at: AsyncWiFiManager wifiManager(&server,&dns), because WiFiManager does not include AsyncWiFiManager. The only way I could get this to compile is to use alanswx's repo.

**Comment by chickey** [comment]
I will setup a fresh environment to compile to check as mine compiles without modification.  I do have AsyncWiFiManager manually installed however.

**Comment by Elwell** [comment]
I've just come across a similar variant of this - A fresh install (1.18.3) of the arduino software with no existing libraries fails to build. The built-in library manager will allow downloading of ESPUI, ModbusMaster, PubSubClient. ESPAsyncWebserver (and its dependent ESPAsyncTCP) needed to be downloaded directly from github, and the "preferred" version of the wifi manager seems to be ESPAsync_WiFiManager - note the underscore!.

I've got a minor patch to this in one of my branches (see https://github.com/Elwell/RS485-WiFi-EPEver/commit/fe32d4986f333e7d6dccc5f1fb24aa0a14170eba) and subsequent comments on discord
